### ISSUE TITLE
Released 1.0.0?

### ISSUE THREAD

**Issue by OrangeDog** [webjars/jquery#109]
Not sure how, but the latest release on Apr 2nd was 1.0.0.
I was expecting to see 3.5.0, although that wasn't announced until Apr 10th.

**Comment by jamesward** [comment]
There was a request for it (#108) and it didn't exist already.
There is a new request for 3.5.0 (#110) which I'll do shortly.

**Comment by OrangeDog** [comment]
I see. Where are all these badly formatted and duplicate XXX issues coming from?
It looks like a random script, but they're all from different users.

**Comment by jamesward** [comment]
That is a good question.  User's are directed from the https://www.webjars.org site to the issue creation page when then click the + button.  But they still need to be signed into github and actually create the issue.  My guess is that people are just confused, but I'm not sure why.

**Comment by OrangeDog** [comment]
Ah I see the template is there, not an actual GitHub issue template.

**Comment by jamesward** [comment]
This mostly happens on Bootstrap & jQuery so maybe I can use an issue creation template to help the confused people.

**Comment by mjeffrey** [comment]
Thanks for the release. It has fixed our vulnerability checker issue.
The current procedure seemed very clear to me... (I thought it was impressive even!)
