### ISSUE TITLE
On MacOS X the maven deployed artefact provokes a java.util.zip.ZipException

### ISSUE THREAD

**Issue by britzke** [webjars/jquery#33]
This prevents the servlet container to start. The message is: "java.util.zip.ZipException: invalid END header (bad central directory offset)". On a linux system the servlet container starts without error.
I tested it with eclipse neon.1 in an empty maven project with only the webjars jquery dependency.
I have been able to unpack it with the standard jar tool and if I repack it with jar tool (without a Manifest file as it has been delivered), the ZipException disappears.

My scenario: MacOS X 10.12.1, Tomcat 8.5.8, Java 1.8.0_111

Can this be a packing/delivering issue?

**Comment by jamesward** [comment]
Which artifact & version is this for?

**Comment by britzke** [comment]
3.1.1 (sorry)

**Comment by jamesward** [comment]
For the Classic `org.webjars` one? (i.e. not NPM or Bower)

**Comment by britzke** [comment]
The classic one.
I loaded it via a maven dependency:
`		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>angularjs</artifactId>
			<version>1.5.8</version>
		</dependency>
`

**Comment by jamesward** [comment]
I think that this should be fixed in `3.1.1-1`.  Let me know if you have any problems.  Thanks!
